@IsTest
private class aos_OneDriveCheckIsExistFolderProcTest {
    @IsTest
    static void testBehavior() {
//        vertic_Response response = new OneDriveCheckIsExistFolderProc().process(
//            new Map<String, Object> {
//                'driveId' => '11111',
//                'newOneDriveFolderName' => 'Test folder'
//            }
//        );
//        System.assertEquals(response.isValid, true);
    }
}