@IsTest(SeeAllData=true)
private class ContactOpportunityRollupHandlerTest {
    static testMethod void testBehavior() {
//        update new Opportunity(
//            Id = '0061y000009ZLXgAAO',
//            StageName = 'Pledged'
//        );
//
//        update new Opportunity(
//            Id = '0061y000009ZLXgAAO',
//            StageName = 'Closed Won'
//        );

//        delete new Opportunity(
//            Id = '0061y000009ZLXgAAO'
//        );
    }
}