@IsTest(SeeAllData=true)
private class ContactCampaignMemberRollupHandlerTest {
    static testMethod void testBehavior() {
//        insert new CampaignMember(
//            Status = 'Attended',
//            CampaignId = '7011y00000088y5AAA',
//            ContactId = '0031y00000VWQwzAAH'
//        );

//        delete new CampaignMember(Id = '00v1y000000vqKlAAI');

//        update new CampaignMember(
//            Id = '00v1y000000vqBoAAI',
//            Status = 'Responded'
//        );
    }
}